FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir requests

# Copy the script
COPY ./scripts/update_usage.py /app/update_usage.py

# Make sure the script is executable
RUN chmod +x /app/update_usage.py

# Run the script
CMD ["python", "/app/update_usage.py"] 