services:
  # Envoy
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:distroless-v1.32.3
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../certs/envoy-ss.crt:/etc/envoy/certs/envoy.crt
      - ../certs/envoy-ss.key:/etc/envoy/certs/envoy.key
      - ../certs/ca.crt:/etc/envoy/certs/ca.crt
    ports:
      - "7379:7379"
    depends_on:
      - state-storage
    networks:
      - state-storage 
  # State Storage (Webdis + Redis)
  state-storage:
    container_name: state-storage
    image: nicolas/webdis:0.1.22
    networks:
      - state-storage
networks:
  state-storage:
