services:
  envoy-service:
    container_name: envoy-service
    image: envoyproxy/envoy:distroless-v1.32.3
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../certs:/etc/envoy/certs
    ports:
      - "8002:8002"